#!/bin/sh -e

mkdir -p ${SYSROOT}/boot/grub
cat > ${SYSROOT}/boot/grub/grub.cfg << __EOF__
set timeout=1
set default=0
menuentry "os" {
  multiboot2 /boot/kernel
  module2 /boot/initrd.img ramdisk
  boot
}
__EOF__

grub-mkrescue -o ${ISO} ${SYSROOT}
